apiVersion: v1
kind: Service
metadata:
  name: elk-test-01-elastic-lb
spec: 
  selector:
    app: elasticsearch
    release: elk-test-01-elastic
    role: coordinating-only
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: LoadBalancer