apiVersion: v1
apiVersion: v1
kind: Service
metadata:
  name: elk-test-01-kibana-lb
spec: 
  selector:
    app: kibana
    release: elk-test-01
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  type: LoadBalancer