apiVersion: v1
apiVersion: v1
kind: Service
metadata:
  name: opendistro-elastic-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:076655312027:certificate/2168cc9b-109d-4965-8b58-87ea4b276404
spec: 
  selector:
    role: client
    app: opendistro-opendistro-es
spec: 
  selector:
    app: elasticsearch
    role: client
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: LoadBalancer