apiVersion: v1
apiVersion: v1
kind: Service
metadata:
  name: opendistro-elastic-lb
spec: 
  selector:
    app: elasticsearch
    role: client
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  type: LoadBalancer