apiVersion: v1
apiVersion: v1
kind: Service
metadata:
  name: opendistro-kibana-lb
spec: 
  selector:
    role: kibana
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5601
  type: LoadBalancer
