apiVersion: v1
kind: Service
metadata:
  name: ics-wptest-wordpress-aws 
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-1:076655312027:certificate/2168cc9b-109d-4965-8b58-87ea4b276404
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"

spec: 
  selector:
    app.kubernetes.io/instance: wp-cust01
    app.kubernetes.io/name: wordpress
  ports:
    - name: https
      port: 443
      targetPort: 8080
    - name: http
      port: 80
      targetPort: 8080
  type: LoadBalancer